"""rename department

Revision ID: 81825ff6bca9
Revises: f838b71acc4e
Create Date: 2024-06-03 21:03:12.714803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81825ff6bca9'
down_revision = 'f838b71acc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments', 'department')
    # ### end Alembic commands ###
